### ISSUE TITLE
License

### ISSUE THREAD

**Issue by machawk1** [edsu/inst341#1]
Hi @edsu. I continue to be inspired by your presentation of this topic and hope to incorporate some of the material into the revision of a Curation course I will teach in the future.

With that in mind, do you or UMD own the material in this repo? Can you provide a license for reuse?

Thanks!

**Comment by edsu** [comment]
Thanks for the kind words, and the good idea to add a license! Would CC-BY be ok? If you want to contribute I would add your name to the license.

**Comment by machawk1** [comment]
@edsu CC-BY would be great. I have submitted PR #2 using this license.
